export const wilayas = [
  { value: '01', label: '01 - أدرار' },
  { value: '02', label: '02 - الشلف' },
  { value: '03', label: '03 - الأغواط' },
  { value: '04', label: '04 - أم البواقي' },
  { value: '05', label: '05 - باتنة' },
  { value: '06', label: '06 - بجاية' },
  { value: '07', label: '07 - بسكرة' },
  { value: '08', label: '08 - بشار' },
  { value: '09', label: '09 - البليدة' },
  { value: '10', label: '10 - البويرة' },
  { value: '11', label: '11 - تمنراست' },
  { value: '12', label: '12 - تبسة' },
  { value: '13', label: '13 - تلمسان' },
  { value: '14', label: '14 - تيارت' },
  { value: '15', label: '15 - تيزي وزو' },
  { value: '16', label: '16 - الجزائر' },
  { value: '17', label: '17 - الجلفة' },
  { value: '18', label: '18 - جيجل' },
  { value: '19', label: '19 - سطيف' },
  { value: '20', label: '20 - سعيدة' },
  { value: '21', label: '21 - سكيكدة' },
  { value: '22', label: '22 - سيدي بلعباس' },
  { value: '23', label: '23 - عنابة' },
  { value: '24', label: '24 - قالمة' },
  { value: '25', label: '25 - قسنطينة' },
  { value: '26', label: '26 - المدية' },
  { value: '27', label: '27 - مستغانم' },
  { value: '28', label: '28 - المسيلة' },
  { value: '29', label: '29 - معسكر' },
  { value: '30', label: '30 - ورقلة' },
  { value: '31', label: '31 - وهران' },
  { value: '32', label: '32 - البيض' },
  { value: '33', label: '33 - إليزي' },
  { value: '34', label: '34 - برج بوعريريج' },
  { value: '35', label: '35 - بومرداس' },
  { value: '36', label: '36 - الطارف' },
  { value: '37', label: '37 - تندوف' },
  { value: '38', label: '38 - تيسمسيلت' },
  { value: '39', label: '39 - الوادي' },
  { value: '40', label: '40 - خنشلة' },
  { value: '41', label: '41 - سوق أهراس' },
  { value: '42', label: '42 - تيبازة' },
  { value: '43', label: '43 - ميلة' },
  { value: '44', label: '44 - عين الدفلى' },
  { value: '45', label: '45 - النعامة' },
  { value: '46', label: '46 - عين تيموشنت' },
  { value: '47', label: '47 - غرداية' },
  { value: '48', label: '48 - غليزان' },
  { value: '49', label: '49 - تيميمون' },
  { value: '50', label: '50 - برج باجي مختار' },
  { value: '51', label: '51 - أولاد جلال' },
  { value: '52', label: '52 - بني عباس' },
  { value: '53', label: '53 - عين صالح' },
  { value: '54', label: '54 - عين قزام' },
  { value: '55', label: '55 - توقرت' },
  { value: '56', label: '56 - جانت' },
  { value: '57', label: '57 - المغير' },
  { value: '58', label: '58 - المنيعة' },
]
